[package]
name        = "example-server"
description = "logfx を HTTP サーバに組み込む形の例"
version     = "0.0.0"
flix        = "0.75.3"
authors     = ["ababup1192 <ababup1192@gmail.com>"]
license     = "Apache-2.0"

[dependencies]
"github:ababup1192/logfx" = { version = "0.2.0", security = "unrestricted" }

[mvn-dependencies]
