#!/usr/bin/env bash
# Run flix doc and shape the output (build/doc/) so it can be put on GitHub Pages.
#
# WhyNot: the output of flix doc is not published as is. The root index.html is the index of the
# Flix Prelude, and as the first thing someone opening the logfx reference sees, it looks like a
# different library. It is replaced, and the original index is kept as prelude.html (because the
# "back" link on every page goes to root).
#
# WhyNot: not only the 5 Logfx pages are published. Type links such as Map[String, Value] point at
# standard library pages, so removing them would make it impossible to go on from a type name.
set -euo pipefail

cd "$(dirname "$0")/.."
version="$(sed -n 's/^version *= *"\(.*\)"/\1/p' flix.toml)"
flix_version="$(sed -n 's/^flix *= *"\(.*\)"/\1/p' flix.toml)"

rm -rf build/doc
bin/flix doc

test -f build/doc/Logfx.html

# Fix the Source links. flix doc writes a URL that simply concatenates the absolute path it was
# given onto the location of its own standard library (.../main/src/library//Users/abab/Desktop/logfx/src/...),
# so as is it 404s. Leaving a local absolute path in the output is a problem in itself.
sed -i.bak \
    -e "s|https://github.com/flix/flix/blob/master/main/src/library/$PWD/|https://github.com/ababup1192/logfx/blob/v${version}/|g" \
    build/doc/Logfx*.html
rm -f build/doc/Logfx*.html.bak

mv build/doc/index.html build/doc/prelude.html
# Fix the links in prelude.html that point at itself (the "back" link and the heading).
sed -i.bak "s|href='index.html'|href='prelude.html'|g" build/doc/prelude.html
rm -f build/doc/prelude.html.bak

cat > build/doc/index.html <<HTML
<!doctype html><html lang='en'>
<head>
<meta charset='utf-8'>
<meta name='viewport' content='width=device-width,initial-scale=1'>
<meta name='description' content='API reference for logfx ${version}: structured logging for Flix.'>
<link href='styles.css' rel='stylesheet'>
<link href='favicon.png' rel='icon'>
<title>logfx | API reference</title>
</head>
<body class='no-script'>
<header><div class='flix'><h2><a href='index.html'>logfx</a></h2><span class='version'>${version}</span></div></header>
<main>
<h1>logfx ${version}</h1>
<div class='box'>
<div class='doc'>
<p>Structured logging for <a href='https://flix.dev'>Flix</a>. Lines are emitted through a
<code>Logfx</code> effect; where they go is a plain value (<code>Sink</code>) you compose and swap.</p>
<p>Start at <a href='https://github.com/ababup1192/logfx#readme'>the README</a> — it has the
install line, the examples, and the reasons. This is the generated API reference for
version ${version}, built with Flix ${flix_version}.</p>
</div>
</div>
<h2>Modules</h2>
<div class='box'><div class='doc'><ul>
<li><a href='Logfx.html'>Logfx</a> — the effect, the six severities, <code>runWith</code> / <code>runWithMin</code> / <code>runWithList</code>, <code>withFields</code>, <code>exception</code>, <code>toJsonLine</code>, <code>parseSeverity</code></li>
<li><a href='Logfx.Fields.html'>Logfx.Fields</a> — the field builder</li>
<li><a href='Logfx.Sink.html'>Logfx.Sink</a> — <code>json</code> / <code>silent</code> / <code>collect</code>, composed with <code>minSeverity</code> / <code>enrich</code> / <code>tee</code> / <code>fallback</code></li>
<li><a href='Logfx.Severity.html'>Logfx.Severity</a></li>
<li><a href='Logfx.Value.html'>Logfx.Value</a></li>
</ul></div></div>
<h2>Also here</h2>
<div class='box'><div class='doc'>
<p>The <a href='prelude.html'>Flix standard library</a> is published alongside it, so that the type
links out of the pages above resolve. It is generated by the same Flix ${flix_version} and is not
part of logfx.</p>
</div></div>
</main>
</body>
</html>
HTML

echo "build/doc/ is ready ($(find build/doc -name '*.html' | wc -l | tr -d ' ') pages)"
