#!/usr/bin/env bash
# flix doc を走らせて、GitHub Pages に置ける形（build/doc/）にする。
#
# WhyNot: flix doc の出力をそのまま公開しない。root の index.html は Flix の Prelude の
# 索引で、logfx のリファレンスを開いた人が最初に見る物としては別のライブラリに見える。
# 差し替えた上で、元の索引は prelude.html に残す（全ページの "back" が root に来るため）。
#
# WhyNot: Logfx の 5 ページだけを公開しない。Map[String, Value] のような型のリンクが
# 標準ライブラリのページを指しているので、消すと型名から先に進めなくなる。
set -euo pipefail

cd "$(dirname "$0")/.."
version="$(sed -n 's/^version *= *"\(.*\)"/\1/p' flix.toml)"
flix_version="$(sed -n 's/^flix *= *"\(.*\)"/\1/p' flix.toml)"

rm -rf build/doc
bin/flix doc

test -f build/doc/Logfx.html

# Source のリンクを直す。flix doc は自分の標準ライブラリの置き場に、渡された絶対パスを
# そのまま繋いだ URL を書くので（.../main/src/library//Users/abab/Desktop/logfx/src/...）、
# そのままだと 404 になる。手元の絶対パスが残る事自体も困る。
sed -i.bak \
    -e "s|https://github.com/flix/flix/blob/master/main/src/library/$PWD/|https://github.com/ababup1192/logfx/blob/v${version}/|g" \
    build/doc/Logfx*.html
rm -f build/doc/Logfx*.html.bak

mv build/doc/index.html build/doc/prelude.html
# prelude.html の中の自分自身へのリンク（"back" と見出し）を直す。
sed -i.bak "s|href='index.html'|href='prelude.html'|g" build/doc/prelude.html
rm -f build/doc/prelude.html.bak

cat > build/doc/index.html <<HTML
<!doctype html><html lang='en'>
<head>
<meta charset='utf-8'>
<meta name='viewport' content='width=device-width,initial-scale=1'>
<meta name='description' content='API reference for logfx ${version}: structured logging for Flix.'>
<link href='styles.css' rel='stylesheet'>
<link href='favicon.png' rel='icon'>
<title>logfx | API reference</title>
</head>
<body class='no-script'>
<header><div class='flix'><h2><a href='index.html'>logfx</a></h2><span class='version'>${version}</span></div></header>
<main>
<h1>logfx ${version}</h1>
<div class='box'>
<div class='doc'>
<p>Structured logging for <a href='https://flix.dev'>Flix</a>. Lines are emitted through a
<code>Logfx</code> effect; where they go is a plain value (<code>Sink</code>) you compose and swap.</p>
<p>Start at <a href='https://github.com/ababup1192/logfx#readme'>the README</a> — it has the
install line, the examples, and the reasons. This is the generated API reference for
version ${version}, built with Flix ${flix_version}.</p>
</div>
</div>
<h2>Modules</h2>
<div class='box'><div class='doc'><ul>
<li><a href='Logfx.html'>Logfx</a> — the effect, the six severities, <code>runWith</code> / <code>runWithMin</code> / <code>runWithList</code>, <code>withFields</code>, <code>exception</code>, <code>toJsonLine</code>, <code>parseSeverity</code></li>
<li><a href='Logfx.Fields.html'>Logfx.Fields</a> — the field builder</li>
<li><a href='Logfx.Sink.html'>Logfx.Sink</a> — <code>json</code> / <code>silent</code> / <code>collect</code>, composed with <code>minSeverity</code> / <code>enrich</code> / <code>tee</code> / <code>fallback</code></li>
<li><a href='Logfx.Severity.html'>Logfx.Severity</a></li>
<li><a href='Logfx.Value.html'>Logfx.Value</a></li>
</ul></div></div>
<h2>Also here</h2>
<div class='box'><div class='doc'>
<p>The <a href='prelude.html'>Flix standard library</a> is published alongside it, so that the type
links out of the pages above resolve. It is generated by the same Flix ${flix_version} and is not
part of logfx.</p>
</div></div>
</main>
</body>
</html>
HTML

echo "build/doc/ is ready ($(find build/doc -name '*.html' | wc -l | tr -d ' ') pages)"
